export default () => {
  process.env.NEXT_PUBLIC_SUPABASE_URL="https://zbikdhckxnceucjlsmxj.supabase.co"
  process.env.NEXT_PUBLIC_SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaWtkaGNreG5jZXVjamxzbXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTMyNDEwODQsImV4cCI6MTk2ODgxNzA4NH0.H6hR9vMn9H3r7d_p1JEifZMkx2CS8FXs7eycK9hzHPY"
}