import {
  Box,
  Text,
  Heading,
  Container,
  Flex,
  VStack,
  StackDivider,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "reset-css";
import DateTime from "../components/DateTime"

const IndexPage = () => {
  return (
    <Box bg="grey" w="100vw" h="100vh">
      <VStack align="stretch">
        <Box h="30px" w="100%" bg="yellow.200">
          Reserve space for navbar with login on the justifyRight
        </Box>

        <Box>
          <Flex>
            <Box w="150px" h="100%" bg="purple.100">
              <Text>sidebar</Text>
            </Box>
            <Box w="100%" >
              <DateTime />
            </Box>
          </Flex>
        </Box>
      </VStack>
    </Box>

    // <Container maxW="container.xl" p={10} maxH="container.xl">
    //   <Flex h="100vh" py={0} w="100vw">
    //     <VStack
    //       w="50%"
    //       h="full"
    //       p={10}
    //       spacing={10}
    //       alignItems="flex-start"
    //       bg="green.100"
    //     >
    //       hello
    //     </VStack>
    //     <VStack
    //       w="50%"
    //       h="full"
    //       p={10}
    //       spacing={10}
    //       alignItems="flex-start"
    //       bg="purple"
    //     >
    //       hello
    //     </VStack>
    //   </Flex>
    // </Container>

    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   {/* Metadata and nav */}

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Project Flow</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{" "}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>
    //   </main>

    //   {/* Footer Below Bar */}
    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{" "}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  );
};

export default IndexPage;
